[package]
name = "workstealing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
rayon = "1.5.3"
affinity = "0.1.2"
num-format = "0.4.4"

[profile.dev]
opt-level = 3
